# Generated by Django 6.0.7 on 2026-08-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='expert_profiles', to='categories.subcategory'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory'),
        ),
    ]
