# Generated by Django 6.0.7 on 2026-08-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
