# Generated by Django 6.0.7 on 2026-08-22 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_expertprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='share_whatsapp_with_clients',
            field=models.BooleanField(default=False, help_text='Allow booked clients to see your WhatsApp number'),
        ),
        migrations.CreateModel(
            name='ExpertCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.expertprofile')),
            ],
        ),
    ]
