# Generated by Django 6.0.7 on 2026-08-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_notification_sessionbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
