# Generated by Django 6.0.7 on 2026-08-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertavailability',
            options={'ordering': ['date', 'day_of_week', 'start_time'], 'verbose_name_plural': 'Expert Availabilities'},
        ),
        migrations.AlterUniqueTogether(
            name='expertavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='expertavailability',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='expertavailability',
            name='is_recurring',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='expertavailability',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
