# Generated by Django 6.0.7 on 2026-08-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_expertavailability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
